Changes for the Vue App
tallence/core-forms pull request #60
Opened 2020-09-23 06:18 UTC by svkroschwald

Backend changes required for the CoreForms VueJS Sample Theme

2021-01-24 13:39 UTC, TallenceJanHendrikPopp requested changes

2021-01-24 13:39 UTC, TallenceJanHendrikPopp commented on form-editor-cae/src/main/java/com/tallence/formeditor/cae/elements/CheckBoxesGroup.java
> +    return checkBoxes.stream().filter(cv -> values.contains(cv.getValue())).collect(Collectors.toList());
Finde cv als Variablennamen etwas ungünstig. Ist durch die Abkürzung meiner Meinung nach etwas langsamer zu verstehen. Kann aber so bleiben.

2021-01-24 13:39 UTC, TallenceJanHendrikPopp commented on form-editor-cae/src/main/java/com/tallence/formeditor/cae/elements/CheckBoxesGroup.java
> +  private void getValues() {
Wozu ist hier die Methode notwendig?

2021-01-24 13:39 UTC, TallenceJanHendrikPopp commented on form-editor-cae/src/main/java/com/tallence/formeditor/cae/handler/FormConfigController.java
> +  public static final String FORM_EDITOR_CONFIG_URL = FORMS_ROOT_URL_SEGMENT + "/" + FORM_EDITOR_CONFIG_VIEW + "/{currentContext}/{editor}";
Auch nicht zwingend notwendig (und vielleicht etwas kleinlich), aber ich finde es schöner, wenn die public Variablen immer oben stehen.

2021-01-24 13:39 UTC, TallenceJanHendrikPopp commented on form-editor-cae/src/main/java/com/tallence/formeditor/cae/handler/FormConfigController.java
> +      return "";
Vielleicht könnte man hier auch eine ResponseStatusException von Spring nutzen, sodass anstelle eines leeren Bodys auch ein JSON mit einer Fehlermeldung zurückgegeben wird?

2021-01-24 13:39 UTC, TallenceJanHendrikPopp commented on form-editor-cae/src/main/java/com/tallence/formeditor/cae/handler/FormConfigController.java
> +    if (currentContext == null) {
Kann das null sein? Der currentContext kommt ja durch die Path-Variable rein die per default required ist. Wenn der null wäre, würde ja vorher schon eine Exception durch Spring fliegen, oder?

2021-01-24 13:39 UTC, TallenceJanHendrikPopp commented on form-editor-cae/src/main/java/com/tallence/formeditor/cae/handler/FormController.java
> +public class FormController  {
Ein Leerzeichen zu viel, aber auch nicht so schlimm :D

2021-01-24 13:39 UTC, TallenceJanHendrikPopp commented on form-editor-cae/src/main/java/com/tallence/formeditor/cae/handler/FormController.java
> +  private Navigation getNavigationForContext(CMChannel currentContext) {
Wenn die Methode trotzdem notwendig ist (siehe Kommentar weiter oben), wurde diese öfter dupliziert, kann man die irgendwo anders hinziehen, sodass der Code wiederverwendet wird, oder ist das nicht so einfach möglich?

2021-01-24 13:39 UTC, TallenceJanHendrikPopp commented on form-editor-cae/src/main/java/com/tallence/formeditor/cae/serializer/FormElementSerializerBase.java
> +    gen.writeStringField("id", field.getId());
Gibt es für id und technicalName auch Konstanten, die wir verwenden könnten?

2021-01-24 13:39 UTC, TallenceJanHendrikPopp commented on form-editor-cae/src/main/java/com/tallence/formeditor/cae/serializer/FormElementSerializerBase.java
> +    if (field instanceof FieldWithOptions) {
Können wir hier auch für name, options id etc. auch die Konstanten verwenden? Oder gibt es hierfür noch keine?

2021-01-24 13:39 UTC, TallenceJanHendrikPopp commented on form-editor-cae/src/main/java/com/tallence/formeditor/cae/serializer/TextAreaSerializerFactory.java
> +        gen.writeNumberField("rows", field.getRows());
Hier evtl. auch Konstanten verwenden?

2021-01-24 13:39 UTC, TallenceJanHendrikPopp commented on form-editor-cae/src/main/java/com/tallence/formeditor/cae/serializer/TextOnlySerializerFactory.java
> +      gen.writeStringField("id", field.getId());
Da der String jetzt öfters verwendet wurde, sollten wir definitiv Konstanten verwenden / anlegen.

2021-01-24 13:39 UTC, TallenceJanHendrikPopp commented on form-editor-cae/src/main/java/com/tallence/formeditor/cae/validator/DateFieldValidator.java
>      try {
Mh, hier wird drei Mal der gleiche Code verwendet, mit nur einem anderen Datumsformat. Wäre es besser hier eventuell über eine Liste konfigurierter Formate zu iterieren?

2021-01-24 13:39 UTC, TallenceJanHendrikPopp commented on form-editor-cae/src/test/java/com/tallence/formeditor/cae/handler/FormConfigControllerTest.java
> +    //TODO check for formatted dateString
Ist das noch ein offenes ToDo oder eher etwas für später?

2021-01-25 10:33 UTC, timolemke commented on form-editor-cae/src/main/java/com/tallence/formeditor/cae/handler/FormConfigController.java
> +  public static final String FORM_EDITOR_CONFIG_URL = FORMS_ROOT_URL_SEGMENT + "/" + FORM_EDITOR_CONFIG_VIEW + "/{currentContext}/{editor}";
Die nutzt aber die anderen Konstanten, die nicht public sind...

2021-01-25 10:52 UTC, timolemke commented on form-editor-cae/src/main/java/com/tallence/formeditor/cae/validator/DateFieldValidator.java
>      try {
Das sind static Methoden an den jeweiligen Klassen, die erben nicht voneinander.

2021-01-25 10:55 UTC, timolemke commented on form-editor-cae/src/test/java/com/tallence/formeditor/cae/handler/FormConfigControllerTest.java
> +    //TODO check for formatted dateString
Naja, das sollte man schon noch machen. Ist aber komplizierter, da die Daten ja abhängig vom aktuellen Timestamp sind. Wäre also ein ToDo für später

2021-01-25 12:50 UTC, TallenceJanHendrikPopp approved these changes

2021-01-25 13:10 UTC, merged